# Generated by Django 5.0.7 on 2024-08-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='publish_date',
            field=models.DateField(default='2022-01-01'),
        ),
    ]
